/** Local bookmarks / reminders / reports (IndexedDB, not encrypted — optional later). */

export interface Bookmark {
  id: string;
  url: string;
  title: string;
  note?: string;
  createdAt: string;
}

export interface Reminder {
  id: string;
  text: string;
  atIso: string;
  createdAt: string;
  fired?: boolean;
}

export interface ReportArtifact {
  id: string;
  title: string;
  bodyHtml: string;
  createdAt: string;
}

function openDb(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open("combo_x_artifacts", 1);
    req.onupgradeneeded = () => {
      const db = req.result;
      for (const name of ["bookmarks", "reminders", "reports"]) {
        if (!db.objectStoreNames.contains(name)) db.createObjectStore(name, { keyPath: "id" });
      }
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error ?? new Error("artifacts db open failed"));
  });
}

function idbReq<T>(req: IDBRequest<T>): Promise<T> {
  return new Promise((resolve, reject) => {
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error ?? new Error("idb failed"));
  });
}

export class ArtifactStore {
  private db: IDBDatabase | null = null;

  private async getDb(): Promise<IDBDatabase> {
    if (!this.db) this.db = await openDb();
    return this.db;
  }

  private store(name: string, mode: IDBTransactionMode): IDBObjectStore {
    if (!this.db) throw new Error("db not open");
    return this.db.transaction(name, mode).objectStore(name);
  }

  async saveBookmark(input: { url: string; title: string; note?: string }): Promise<Bookmark> {
    const row: Bookmark = {
      id: crypto.randomUUID(),
      url: input.url,
      title: input.title,
      note: input.note,
      createdAt: new Date().toISOString(),
    };
    await this.getDb();
    await idbReq(this.store("bookmarks", "readwrite").put(row));
    return row;
  }

  async listBookmarks(): Promise<Bookmark[]> {
    await this.getDb();
    return idbReq(this.store("bookmarks", "readonly").getAll());
  }

  async setReminder(input: { text: string; atIso: string }): Promise<Reminder> {
    const row: Reminder = {
      id: crypto.randomUUID(),
      text: input.text,
      atIso: input.atIso,
      createdAt: new Date().toISOString(),
    };
    await this.getDb();
    await idbReq(this.store("reminders", "readwrite").put(row));
    return row;
  }

  async listReminders(): Promise<Reminder[]> {
    await this.getDb();
    return idbReq(this.store("reminders", "readonly").getAll());
  }

  async markReminderFired(id: string): Promise<void> {
    await this.getDb();
    const row = await idbReq<Reminder | undefined>(this.store("reminders", "readonly").get(id));
    if (!row) return;
    row.fired = true;
    await idbReq(this.store("reminders", "readwrite").put(row));
  }

  /** Due reminders that have not fired yet. */
  async dueReminders(now = Date.now()): Promise<Reminder[]> {
    const all = await this.listReminders();
    return all.filter((r) => !r.fired && Date.parse(r.atIso) <= now);
  }

  async saveReport(input: { title: string; bodyHtml: string }): Promise<ReportArtifact> {
    const row: ReportArtifact = {
      id: crypto.randomUUID(),
      title: input.title,
      bodyHtml: input.bodyHtml,
      createdAt: new Date().toISOString(),
    };
    await this.getDb();
    await idbReq(this.store("reports", "readwrite").put(row));
    return row;
  }

  async listReports(): Promise<ReportArtifact[]> {
    await this.getDb();
    const rows = await idbReq<ReportArtifact[]>(this.store("reports", "readonly").getAll());
    return rows.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  }
}

export function buildReportHtml(title: string, bodyHtml: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"/><title>${escapeHtml(title)}</title>
<style>body{font-family:system-ui,sans-serif;max-width:720px;margin:2rem auto;padding:0 1rem;line-height:1.5}
h1{font-size:1.4rem}</style></head>
<body><h1>${escapeHtml(title)}</h1>${bodyHtml}
<footer style="margin-top:2rem;color:#666;font-size:12px">Generated by Combo-X · ${new Date().toISOString()}</footer>
</body></html>`;
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!,
  );
}
