/** Tool allowlist groups for Settings / Tools tabs. */
export const TOOL_GROUPS = {
  Browser: [
    "page_digest",
    "get_page",
    "get_links",
    "get_interactive",
    "click_index",
    "type_index",
    "click",
    "type_text",
    "extract",
    "query_all",
    "scrape_tables",
    "scroll",
    "wait",
    "find_text",
    "navigate",
    "go_back",
    "list_tabs",
    "open_tab",
    "activate_tab",
    "close_tab",
    "login",
    "save_site_profile",
    "get_site_profile",
    "scrape_catalog",
    "ensure_scrape_table",
    "upsert_scrape_rows",
    "get_scrape_table",
    "scrape_pdps",
  ],
  Data: [
    "parse_data",
    "rag_search",
    "rag_read_file",
    "rag_status",
    "list_attachments",
    "read_attachment",
    "export_csv",
    "save_view",
    "list_views",
    "get_view",
  ],
  Media: [
    "screenshot_viewport",
    "screenshot_element",
    "screenshot_full",
    "start_recording",
    "stop_recording",
  ],
  Memory: [
    "remember",
    "save_memory",
    "recall",
    "memory_list",
    "skill_search",
    "skill_read",
    "skill_save",
    "save_bookmark",
    "set_reminder",
    "create_report",
    "search_sessions",
  ],
  Connectors: ["rest_request", "mcp_list_tools", "mcp_call"],
  Agentic: ["create_agent", "update_agent", "list_agents", "spawn_subagent"],
  Meta: ["create_task", "update_task", "list_tasks"],
  PageExt: [
    "create_page_extension",
    "update_page_extension",
    "list_page_extensions",
    "get_page_extension",
    "approve_page_extension",
    "revoke_page_extension",
    "inject_page_extension",
    "set_page_extension_bridge",
    "page_ext_data_list",
    "page_ext_data_get",
    "page_ext_data_clear",
    "list_page_extension_audit",
  ],
} as const;

export type ToolGroupName = keyof typeof TOOL_GROUPS;

export const GROUP_ORDER: ToolGroupName[] = [
  "Browser",
  "Data",
  "Media",
  "Memory",
  "Connectors",
  "Agentic",
  "Meta",
  "PageExt",
];
