/** Tool allowlist groups for Settings / Tools tabs. */

/** Combo voice / Mac / portfolio tools. */
export const COMBO_VOICE_TOOLS = [
  "portfolio_ask",
  "portfolio_search",
  "mac_ui_tree",
  "mac_screenshot",
  "mac_click",
  "mac_type",
  "mac_key",
  "mac_apps",
  "mac_focus",
  "mac_list_dir",
  "mac_read_file",
  "index_dir",
  "ambient_recall",
] as const;

/** @deprecated use COMBO_VOICE_TOOLS */
export const JARVIS_TOOLS = COMBO_VOICE_TOOLS;

export const TOOL_GROUPS = {
  Browser: [
    "page_digest",
    "get_page",
    "get_links",
    "get_interactive",
    "press_key",
    "click_index",
    "type_index",
    "click",
    "type_text",
    "extract",
    "query_all",
    "scrape_tables",
    "scroll",
    "wait",
    "find_text",
    "web_search",
    "web_fetch",
    "navigate",
    "go_back",
    "list_tabs",
    "open_tab",
    "activate_tab",
    "close_tab",
    "login",
    "save_site_profile",
    "get_site_profile",
    "scrape_catalog",
    "ensure_scrape_table",
    "upsert_scrape_rows",
    "get_scrape_table",
    "scrape_pdps",
  ],
  Data: [
    "parse_data",
    "rag_search",
    "rag_grep",
    "rag_glob",
    "rag_read_file",
    "rag_status",
    "list_attachments",
    "read_attachment",
    "export_csv",
    "save_view",
    "list_views",
    "get_view",
  ],
  Media: [
    "ux_critique",
    "annotate_screenshot",
    "page_css_preview",
    "page_css_clear",
    "screenshot_viewport",
    "screenshot_element",
    "screenshot_full",
    "start_recording",
    "stop_recording",
  ],
  Memory: [
    "remember",
    "save_memory",
    "recall",
    "memory_list",
    "skill_search",
    "skill_read",
    "skill_save",
    "list_custom_tools",
    "custom_tool_save",
    "save_bookmark",
    "set_reminder",
    "create_report",
    "create_map_report",
    "open_preview",
    "search_sessions",
    "get_session",
    "export_session",
  ],
  Connectors: [
    "list_connectors",
    "save_rest_connector",
    "ensure_github_connector",
    "dispatch_cursor_agent",
    "rest_request",
    "mcp_list_tools",
    "mcp_call",
    "publish_upload",
  ],
  Agentic: ["create_agent", "update_agent", "list_agents", "spawn_subagent"],
  Meta: ["create_task", "update_task", "list_tasks", "reorder_tasks"],
  PageExt: [
    "create_page_extension",
    "update_page_extension",
    "list_page_extensions",
    "get_page_extension",
    "approve_page_extension",
    "revoke_page_extension",
    "inject_page_extension",
    "set_page_extension_bridge",
    "page_ext_data_list",
    "page_ext_data_get",
    "page_ext_data_clear",
    "list_page_extension_audit",
  ],
  "Voice mode": [...COMBO_VOICE_TOOLS],
};

export type ToolGroupName = keyof typeof TOOL_GROUPS;

export const GROUP_ORDER: ToolGroupName[] = [
  "Browser",
  "Data",
  "Media",
  "Memory",
  "Connectors",
  "Agentic",
  "Meta",
  "PageExt",
  "Voice mode",
];
